name: "Spanet Spa Bridge"
version: "1.0.0"
slug: "spanet"
description: "HTTP API and Home Assistant MQTT bridge for Spanet-controlled spas"
url: "https://github.com/freman/spanet"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "spalink HTTP API"
services:
  - mqtt:want
options:
  spa: ""
  mqtt_node_id: "spanet"
  mqtt_poll_interval: 15
schema:
  spa: "str"
  mqtt_node_id: "str"
  mqtt_poll_interval: "int(5,300)"
